import os
import base64
from PIL import Image

# Custom Message for Text Portrait
CUSTOM_MESSAGE = "Happy Birthday and Happy Valentine's Day to the most beautiful girl. You are the light of my life, the beat of my heart, and the reason I smile every day. Wishing you all the love and happiness in the world. "

def image_to_html_text_portrait(image_path, width=120):
    try:
        img = Image.open(image_path)
    except Exception as e:
        print(f"Unable to open image: {e}")
        return ""

    # Calculate height to maintain aspect ratio
    # Font aspect ratio correction (approx 0.55 for monospace fonts)
    aspect_ratio = img.height / img.width
    new_height = int(width * aspect_ratio * 0.55)
    img = img.resize((width, new_height))
    
    # Ensure image is RGB to extract colors
    img = img.convert('RGB')
    pixels = img.load()
    
    html_lines = []
    msg_len = len(CUSTOM_MESSAGE)
    char_index = 0
    
    # Wrap in a container that ensures monospace and correct background
    # Removing padding and inline styles that might interfere with full-screen CSS
    html_lines.append('<div class="text-portrait-container">')
    
    for y in range(new_height):
        line_html = ""
        for x in range(width):
            r, g, b = pixels[x, y]
            
            # Select character from message
            char = CUSTOM_MESSAGE[char_index % msg_len]
            char_index += 1
            
            # Brightness calculation (standard luminance)
            brightness = (r * 0.299 + g * 0.587 + b * 0.114)
            
            # Create span with color
            if brightness < 30:
                # Boost dark areas more for better visibility on black background
                line_html += f'<span style="color:rgba({r+40},{g+40},{b+40},0.2)">{char}</span>'
            elif brightness < 80:
                # Mid-tones boost
                line_html += f'<span style="color:rgba({r+30},{g+30},{b+30},0.6)">{char}</span>'
            else:
                # Visible areas - keep them bright
                line_html += f'<span style="color:rgb({r},{g},{b})">{char}</span>'
        
        html_lines.append(line_html + "<br>")
    
    html_lines.append('</div>')
    return "\n".join(html_lines)

def generate_html():
    # 1. Generate Text Portrait
    ascii_art = ""
    if os.path.exists("portrait.jpg"):
        print("Generating Text Portrait from portrait.jpg...")
        # Increase width for higher resolution full-screen impact
        ascii_art = image_to_html_text_portrait("portrait.jpg", width=200)
    else:
        print("Warning: portrait.jpg not found.")
        ascii_art = "<div style='color:white'>Portrait not found</div>"

    # Generate a smaller version for the corner
    corner_ascii = ""
    if os.path.exists("portrait.jpg"):
        print("Generating smaller ASCII art for corner...")
        corner_ascii = image_to_html_text_portrait("portrait.jpg", width=60)

    # 2. Write to portrait_data.js
    # We'll store the ASCII art in a global variable that index.html can access
    js_content = f"""
// This file is auto-generated by generate_static_html.py
// It contains the ASCII art data for the portrait
window.PORTRAIT_ASCII = `{ascii_art.replace('`', '\\`')}`;
window.CORNER_ASCII = `{corner_ascii.replace('`', '\\`')}`;

// Function to inject ASCII art into the page
function injectPortraitData() {{
    const mainContainer = document.getElementById('portrait-container');
    if (mainContainer) {{
        mainContainer.innerHTML = window.PORTRAIT_ASCII;
    }}
    
    const celebrationContainer = document.getElementById('celebration-portrait-container');
    if (celebrationContainer) {{
        celebrationContainer.innerHTML = window.CORNER_ASCII;
    }}
    
    const cornerContainer = document.getElementById('ascii-portrait');
    if (cornerContainer) {{
        cornerContainer.innerHTML = window.CORNER_ASCII;
    }}
}}

// Run injection when DOM is ready
if (document.readyState === 'loading') {{
    document.addEventListener('DOMContentLoaded', injectPortraitData);
}} else {{
    injectPortraitData();
}}
"""
    
    with open('portrait_data.js', 'w') as f:
        f.write(js_content)
    
    print("Success! Created portrait_data.js with ASCII Art data.")
    print("Now index.html can simply include <script src='portrait_data.js'></script> to show the image.")

if __name__ == "__main__":
    generate_html()
